<script setup lang="ts">
import { onMounted,ref } from 'vue';import { showConfirmDialog,showFailToast,showSuccessToast } from 'vant';import PageHeader from '../components/PageHeader.vue';import EmptyState from '../components/EmptyState.vue';import { deleteRecord,getAdminRecords,getAdminUsers,saveActivity,updateProfile } from '../services/api';import type { Activity,Profile } from '../types'
const tab=ref('users');const users=ref<Profile[]>([]);const records=ref<any[]>([]);const activity=ref<Partial<Activity>>({activity_name:'21天轻盈计划',start_date:new Date().toLocaleDateString('en-CA'),end_date:'',status:'active'});const saving=ref(false)
async function load(){try{[users.value,records.value]=await Promise.all([getAdminUsers(),getAdminRecords()])}catch(e){showFailToast(e instanceof Error?e.message:'加载失败')}}onMounted(load)
async function remove(id:number){await showConfirmDialog({title:'删除记录',message:'此操作不可撤销，确定继续吗？'});await deleteRecord(id);records.value=records.value.filter(r=>r.id!==id);showSuccessToast('已删除')}
function exportCsv(){const head=['日期','昵称','体重','早餐','午餐','晚餐','是否运动','运动类型','运动分钟','饮水ml','睡眠小时','完成','备注'];const lines=records.value.map(r=>[r.record_date,r.profiles?.nickname,r.weight,r.breakfast_status,r.lunch_status,r.dinner_status,r.exercised?'是':'否',r.exercise_type,r.exercise_minutes,r.water_ml,r.sleep_hours,r.completed?'是':'否',r.remark].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','));const blob=new Blob(['\ufeff'+[head.join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`减肥打卡-${new Date().toLocaleDateString('en-CA')}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function saveAct(){if(!activity.value.activity_name||!activity.value.start_date||!activity.value.end_date)return showFailToast('请完整填写活动信息');saving.value=true;try{activity.value=await saveActivity(activity.value);showSuccessToast('活动已保存')}catch(e){showFailToast(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
</script>
<template><section class="page"><PageHeader eyebrow="ADMIN" title="管理后台" back/><div class="admin-tabs"><button :class="{active:tab==='users'}" @click="tab='users'">用户</button><button :class="{active:tab==='records'}" @click="tab='records'">打卡记录</button><button :class="{active:tab==='activity'}" @click="tab='activity'">活动设置</button></div><template v-if="tab==='users'"><div class="card"><div class="row"><strong>成员列表</strong><span class="tag">{{users.length}} 人</span></div><EmptyState v-if="!users.length" text="暂无用户"/><article v-for="u in users" :key="u.id" class="record"><div class="row"><div><strong>{{u.nickname}}</strong><div class="muted">{{u.username}} · {{u.role}}</div></div><van-switch :model-value="u.status==='active'" size="22" @update:model-value="async(v)=>{await updateProfile(u.id,{status:v?'active':'disabled'});u.status=v?'active':'disabled'}"/></div></article><p class="muted">登录账号需在 Supabase Authentication 中创建，避免在浏览器暴露管理员密钥。</p></div></template><template v-else-if="tab==='records'"><div class="row" style="margin-bottom:12px"><span class="muted">共 {{records.length}} 条</span><van-button size="small" type="primary" @click="exportCsv">导出 CSV</van-button></div><div class="card"><EmptyState v-if="!records.length" text="暂无打卡记录"/><article v-for="r in records" :key="r.id" class="record"><div class="row"><div><strong>{{r.profiles?.nickname}} · {{r.weight}} kg</strong><div class="muted">{{r.record_date}} · {{r.exercised?r.exercise_type||'已运动':'未运动'}}</div></div><van-button size="mini" type="danger" plain @click="remove(r.id)">删除</van-button></div></article></div></template><template v-else><div class="card"><van-field v-model="activity.activity_name" label="活动名称"/><van-field v-model="activity.start_date" label="开始日期" type="date"/><van-field v-model="activity.end_date" label="结束日期" type="date"/><van-field v-model.number="activity.target_loss" label="目标减重" type="number" suffix="kg"/><div style="margin-top:20px"><van-button block round type="primary" :loading="saving" @click="saveAct">保存活动</van-button></div></div></template></section></template>
